### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by 1qrobo1** [gooberdood/Cookie-Clicker-CE#1]
This project doesnt run on both cemu and my actual calculator

**Comment by gooberdood** [comment]
Did you jailbreak your calculator? Have you properly installed the CE C libraries and are using the 1.0 build I had sent? The files should be one 8xp and one 8xv, make sure both are on the calculator.

**Comment by gooberdood** [comment]
Issue solved on Cemetech.net, it was this issue
